# We will need sudo to run docker commands
# TODO:

sudo: required

# In case we need python for testing at come
# point.
language: python

# Working with version 3.6
python:
  - "3.6"

# We require docker
services:
  - docker

branches:
  only:
  - master
  - dev
  - qa

# The following are the pipeline stages. They
# are executed in order inside of a VM in a bash
# shell, (thus they use bash syntax).
# 
# This step runs before the install step,
# and is the first step in this case. Here we
# pull down the requisite code from the
# repository.
# 
before_install:
  - git clone https://github.com/ramrod-project/integration-stack

# Second step, install required dependencies.
install:
  - if [ "$TRAVIS_BRANCH" == "master" ]; 
    then export TAG=latest;
    else export TAG=$TRAVIS_BRANCH; fi
  - export LOGLEVEL=DEBUG
  - docker pull ramrodpcp/frontend-ui:$TAG
  - docker pull ramrodpcp/database-brain:$TAG
  - docker pull ramrodpcp/backend-interpreter:$TAG
  - docker pull ramrodpcp/interpreter-plugin:$TAG

# Third step, set up environment and run the stack.
before_script:
  - docker swarm init
  - docker network create --driver=overlay --attachable pcp
  - docker stack deploy -c docker/docker-compose.yml test-stack
  - sleep 6
  - docker stack ps test-stack
  - docker ps -a

# Fourth step, test away!
script:
  - docker run -t --rm --network pcp -v `pwd`/Robot:/opt/robotframework/tests ramrodpcp/robot-framework-xvfb:$TAG

# Cleanup, housekeeping
after_success:
  - docker stack rm test-stack
  - docker ps -a | grep -v CONTAINER | awk '{print $1}' | xargs docker stop

notifications:
  slack: ramrod-project:GDF82rRYDg3KSekrT3GA24qO