# Docker swarm configuration for PCP application stack
# This file contains all of the configurations for
# starting up and running the necessary containers
# as services in a docker stack.

version: "3"

# In a docker swarm, each container is run as a 'service',
# which is managed by docker through the swarm as opposed
# to directly as with regular containers.
#
# These pull from the latest images on the project docker
# hub.
services:
  # Config information for the frontend container service
  frontend:
    image: ramrodpcp/frontend-ui
    container_name: frontend
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - pcp
    ports:
      - 80:8080
    environment:
      - STAGE=${STAGE}
  # Config information for the RethinkDB container service
  database:
    image: ramrodpcp/database-brain
    container_name: rethinkdb
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - pcp
  # Config information for the backend container service
  backend:
    image: ramrodpcp/backend-interpreter
    container_name: interpreter
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - pcp
    # This container requires a couple environment variables
    # to be passed in. These are taken from the environment
    # in which the stack is run.
    environment:
      - STAGE=${STAGE}
      - LOGLEVEL=${LOGLEVEL}
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

# The 'networks' section defines the internal docker
# networks that will be used by the application stack.
networks:
  pcp:
    external: true